### ISSUE TITLE
Build instructions ? 

### ISSUE THREAD

**Issue by loockeeer** [vijaiaeroastro/nastranToJson#2]
Hi I'm trying to build this project but I can't figure out how to do it. 
Will you provide a Makefile soon, or build instructions ?

**Comment by vijaiaeroastro** [comment]
There is a CMakeLists.txt there.. All you have to do is this

```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

If you want to build in _Debug_ mode, in the above syntax, substitute the word `Release` with `Debug`

**Comment by loockeeer** [comment]
Oh thanks ! And sorry I'm not used to C/C++ compiling.

**Comment by vijaiaeroastro** [comment]
Need not apologize. Feel free to ask for help 😃
